### ISSUE TITLE
consider using authentication header and JWT lib

### ISSUE THREAD

**Issue by amitport** [voronianski/express-api-sample#1]
Is there any special reason you use `X-Access-Token: <token>` instead of `Authentication: Bearer <token>`?

Additionally, can this project possibly use something like [jwt-simple](https://github.com/hokaccha/node-jwt-simple), in order to do token code/decode more reliably?

Those things just bothered me on a quick glimpse, but all in all, this looks like a very useful template. Thanks for publishing it!

**Comment by voronianski** [comment]
@amitport thanks!

Regarding token headers, the main reason why I'm using `X-Access-Token` is that it's not standard authentication, for me bearer token is strongly associated with OAuth2.

As for code/encode, I recommend using https://github.com/auth0/node-jsonwebtoken if you would like to have standard JWT token. But for now I would like to have this custom token generation here.
